CREATE TABLE URL_MAPPING
        (
        ID NUMBER(10) NOT NULL,
        SHORT_URL VARCHAR2(500) NOT NULL,
        ORIGINAL_URL VARCHAR2(500) NOT NULL,
        COUNT NUMBER(10) NOT NULL,
        CALL_TIME TIMESTAMP NOT NULL ,
        PRIMARY KEY(ID)
        );